name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '40 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |-
        npm start
        cat README.md
